### ISSUE TITLE
Cats Effect 3 / fs2 3.x migration

### ISSUE THREAD

**Issue by kubukoz** [satabin/fs2-data#106]
Hi! Are there any plans in place to migrate to Cats Effect 3 / fs2 3.x? If there are any blockers, it would be best to catch them before the RCs are being released. Asking for typelevel/cats-effect#1330 :)

**Comment by ybasket** [comment]
Hi @kubukoz,

thank you for asking! We have everything in place and encountered no blockers, our 1.x branch is already on the latest milestones of fs2 3, CE 3 and weaver 0.7. Once all these publish their final versions, we plan on releasing fs2-data 1.0 based on them (tracked in https://github.com/satabin/fs2-data/projects/1).

**Comment by kubukoz** [comment]
ah, I didn't see that then. Thanks for the update!

**Comment by satabin** [comment]
I will publish a 1.0.0-M1 as soon as CSV pipes are merged, so that people can also start testing it if they are interested in it.

**Comment by eltherion** [comment]
Hi! @satabin 
That PR: https://github.com/satabin/fs2-data/pull/137 is merged and I urgently need any -Mx or -RCy released against cats-effect/fs2 3.x. I know it's friday afternoon, but any chances for that weekend? 😅

**Comment by satabin** [comment]
Is a snapshot version ok for you? A new snapshot is published for every merge. This one would be `0.10.0+48-ece54888-SNAPSHOT` I believe.

**Comment by satabin** [comment]
Also please note this is breaking compatibility with 0.10 as this is in preparation for the 1.0 release, which changes the way textual inputs are read.

A first RC will be published once the CSV row refactoring is done.

**Comment by eltherion** [comment]
Works perfectly, thanks!
