### ISSUE TITLE
Custom java.time formats

### ISSUE THREAD

**Issue by ybasket** [satabin/fs2-data#123]
`CellDecoder` and `CellEncoder` have implicit instances for common `java.time` formats in CSVs, but there's no way to use custom formats yet. This could be exposed on the companion objects (non-implicit methods), but should provide a safe and sane signature despite the exceptions involved in date parsing through `java.time`.

Inspired from a question on Gitter: https://matrix.to/#/!GUjuKyYmWZJiiqOfRW:gitter.im/$8WXkYg1Q5SQvNHAwAId14j3_wvoA5DvI9GqZxbNNBnI?via=gitter.im&via=matrix.org

**Comment by brbrown25** [comment]
@ybasket I'd love to help out with this if no one is working it currently

**Comment by ybasket** [comment]
@brbrown25 That'd be awesome, looking forward to your PR!

Don't hesitate to ask here or on Gitter (fs2-data/general) if you run into obstacles.

**Comment by brbrown25** [comment]
I should be able to start on it this weekend!

**Comment by satabin** [comment]
Thanks for the offer! I'm really looking forward having this in fs2-data!
