### ISSUE TITLE
CellDecoder performance

### ISSUE THREAD

**Issue by ingarabr** [satabin/fs2-data#205]
I tried to use the `data-csv` library to parse some large files. Reading them into the `RowF` case class was quite fast but I did get some poor performance during the cell decoder stage. It did occur for both the semi-auto and custom-written decoders. I've located a code path in the `RowF.as[T]` function where it does recreate the `byHeader` value for each field that's extracted. I could not think of a fix for it without any breaking API changes. I'm happy to provide a pull request if we can find a suitable solution.

A temporary workaround for me was to create a wrapper and cache the `byHeader` value and provide a custom decoder. Here's an example:
```
class CachedHeaderRow(val origin: csv.RowF[Some, String])(implicit hasHeaders: HasHeaders[Some, String]) {

  private lazy val byHeader = origin.headers.get.toList.zip(origin.values.toList).toMap

  def as[T](header: String)(implicit decoder: CellDecoder[T]): DecoderResult[T] =
    byHeader.get(header) match {
      case Some(v) => decoder(v)
      case None    => Left(new DecoderError(s"unknown field $header"))
    }
}
```

This decreased the pipeline of reading, parsing, and decoding of 1 000 000 rows with 30 cells from ~100 seconds to ~10 seconds.

**Comment by satabin** [comment]
Hi @ingarabr,

Thanks for reporting. This indeed is a problem that we should address. The field caching looks like a way to go, we will investigate this.

**Comment by satabin** [comment]
You can give `1.0.0+12-17585bdb-SNAPSHOT` a try, it should be better.

**Comment by ingarabr** [comment]
Hi @satabin.

Works like a charm! Thank you for looking into it :-)
