### ISSUE TITLE
Write scalafix migrations for 1.0 release

### ISSUE THREAD

**Issue by satabin** [satabin/fs2-data#32]
With PRs like #31 source code will need some migrations when version 1.0 is released. Let's provide scalafix migrations for this to ease people's life.

**Comment by ybasket** [comment]
Love the idea! Such migration should then also be listed for [Scala Steward](https://github.com/fthomas/scala-steward/blob/master/modules/core/src/main/resources/scalafix-migrations.conf) once ready so people get automatic migrations.

**Comment by satabin** [comment]
This is the spirit.
