### ISSUE TITLE
Errors during CSV decoding should include line number

### ISSUE THREAD

**Issue by Daenyth** [satabin/fs2-data#53]
This will dramatically help make diagnosis easier for people using the library

**Comment by satabin** [comment]
With the current pipes, if we do not want to break source compatibility (only requirement pre-1.0) this leads in explosion of pipes, which I am fine with.

@ybasket we should be smarter when we do #44 to have this built-in, WDYT?

**Comment by satabin** [comment]
To be done together with #44

**Comment by ybasket** [comment]
As it was not tackled in #44, I reopen the issue and will try to get it done before the final 1.0.0 release.
