### ISSUE TITLE
Publish for scala.js

### ISSUE THREAD

**Issue by cquiroz** [satabin/fs2-data#58]
I'm using fs2-data-xml for library that I'd like to cross publish to scala.js.
It seems that it should be possible given the dependencies.
I may try myself but I don't know much about using `mill`.
Tests are problematic though as they use files and that would be harder on Scala.js

**Comment by satabin** [comment]
Hi @cquiroz 

This is a good idea. Having experimenting various problems with mill I am thinking about moving back to sbt anyway, I can take the opportunity to add Scala.JS support when possible.

For the test cases, it's kind of usual that they only run on JVM, I've done this kind of things for another project in the past, so this wouldn't be a problem.

**Comment by cquiroz** [comment]
It would be great to have at least one js test, it could be done with plain strings instead of files.
The main reason for at least a test is to detect linking errors in case an unsupported call is used.

**Comment by satabin** [comment]
The tests depending on files need to be JVM specific, but the other ones can be shared. The tests relying on files are the compliance tests for all three supported formats, I guess it doesn't matter since we mainly want to check linking.
